//
// Generated by Bluespec Compiler (build e76ca21)
//
// On Mon Jul 27 17:50:31 CEST 2020
//
//
// Ports:
// Name                         I/O  size props
// jtag_slave_TDO                 O     1
// jtag_master_00_TCK             O     1
// jtag_master_00_TMS             O     1
// jtag_master_00_TDI             O     1
// jtag_master_01_TCK             O     1
// jtag_master_01_TMS             O     1
// jtag_master_01_TDI             O     1
// jtag_master_02_TCK             O     1
// jtag_master_02_TMS             O     1
// jtag_master_02_TDI             O     1
// jtag_master_03_TCK             O     1
// jtag_master_03_TMS             O     1
// jtag_master_03_TDI             O     1
// jtag_master_04_TCK             O     1
// jtag_master_04_TMS             O     1
// jtag_master_04_TDI             O     1
// jtag_master_05_TCK             O     1
// jtag_master_05_TMS             O     1
// jtag_master_05_TDI             O     1
// jtag_master_06_TCK             O     1
// jtag_master_06_TMS             O     1
// jtag_master_06_TDI             O     1
// jtag_master_07_TCK             O     1
// jtag_master_07_TMS             O     1
// jtag_master_07_TDI             O     1
// jtag_master_08_TCK             O     1
// jtag_master_08_TMS             O     1
// jtag_master_08_TDI             O     1
// jtag_master_09_TCK             O     1
// jtag_master_09_TMS             O     1
// jtag_master_09_TDI             O     1
// jtag_master_10_TCK             O     1
// jtag_master_10_TMS             O     1
// jtag_master_10_TDI             O     1
// jtag_master_11_TCK             O     1
// jtag_master_11_TMS             O     1
// jtag_master_11_TDI             O     1
// jtag_master_12_TCK             O     1
// jtag_master_12_TMS             O     1
// jtag_master_12_TDI             O     1
// jtag_master_13_TCK             O     1
// jtag_master_13_TMS             O     1
// jtag_master_13_TDI             O     1
// jtag_master_14_TCK             O     1
// jtag_master_14_TMS             O     1
// jtag_master_14_TDI             O     1
// jtag_master_15_TCK             O     1
// jtag_master_15_TMS             O     1
// jtag_master_15_TDI             O     1
// ACLK                           I     1 clock
// ARESETN                        I     1 reset
// slave_select                   I     5 reg
// jtag_slave_TCK                 I     1
// jtag_slave_TMS                 I     1
// jtag_slave_TDI                 I     1
// jtag_master_00_TDO             I     1
// jtag_master_01_TDO             I     1
// jtag_master_02_TDO             I     1
// jtag_master_03_TDO             I     1
// jtag_master_04_TDO             I     1
// jtag_master_05_TDO             I     1
// jtag_master_06_TDO             I     1
// jtag_master_07_TDO             I     1
// jtag_master_08_TDO             I     1
// jtag_master_09_TDO             I     1
// jtag_master_10_TDO             I     1
// jtag_master_11_TDO             I     1
// jtag_master_12_TDO             I     1
// jtag_master_13_TDO             I     1
// jtag_master_14_TDO             I     1
// jtag_master_15_TDO             I     1
//
// Combinational paths from inputs to outputs:
//   jtag_slave_TCK -> jtag_master_00_TCK
//   jtag_slave_TCK -> jtag_master_01_TCK
//   jtag_slave_TCK -> jtag_master_02_TCK
//   jtag_slave_TCK -> jtag_master_03_TCK
//   jtag_slave_TCK -> jtag_master_04_TCK
//   jtag_slave_TCK -> jtag_master_05_TCK
//   jtag_slave_TCK -> jtag_master_06_TCK
//   jtag_slave_TCK -> jtag_master_07_TCK
//   jtag_slave_TCK -> jtag_master_08_TCK
//   jtag_slave_TCK -> jtag_master_09_TCK
//   jtag_slave_TCK -> jtag_master_10_TCK
//   jtag_slave_TCK -> jtag_master_11_TCK
//   jtag_slave_TCK -> jtag_master_12_TCK
//   jtag_slave_TCK -> jtag_master_13_TCK
//   jtag_slave_TCK -> jtag_master_14_TCK
//   jtag_slave_TCK -> jtag_master_15_TCK
//   jtag_slave_TMS -> jtag_master_00_TMS
//   jtag_slave_TMS -> jtag_master_01_TMS
//   jtag_slave_TMS -> jtag_master_02_TMS
//   jtag_slave_TMS -> jtag_master_03_TMS
//   jtag_slave_TMS -> jtag_master_04_TMS
//   jtag_slave_TMS -> jtag_master_05_TMS
//   jtag_slave_TMS -> jtag_master_06_TMS
//   jtag_slave_TMS -> jtag_master_07_TMS
//   jtag_slave_TMS -> jtag_master_08_TMS
//   jtag_slave_TMS -> jtag_master_09_TMS
//   jtag_slave_TMS -> jtag_master_10_TMS
//   jtag_slave_TMS -> jtag_master_11_TMS
//   jtag_slave_TMS -> jtag_master_12_TMS
//   jtag_slave_TMS -> jtag_master_13_TMS
//   jtag_slave_TMS -> jtag_master_14_TMS
//   jtag_slave_TMS -> jtag_master_15_TMS
//   jtag_slave_TDI -> jtag_master_00_TDI
//   jtag_slave_TDI -> jtag_master_01_TDI
//   jtag_slave_TDI -> jtag_master_02_TDI
//   jtag_slave_TDI -> jtag_master_03_TDI
//   jtag_slave_TDI -> jtag_master_04_TDI
//   jtag_slave_TDI -> jtag_master_05_TDI
//   jtag_slave_TDI -> jtag_master_06_TDI
//   jtag_slave_TDI -> jtag_master_07_TDI
//   jtag_slave_TDI -> jtag_master_08_TDI
//   jtag_slave_TDI -> jtag_master_09_TDI
//   jtag_slave_TDI -> jtag_master_10_TDI
//   jtag_slave_TDI -> jtag_master_11_TDI
//   jtag_slave_TDI -> jtag_master_12_TDI
//   jtag_slave_TDI -> jtag_master_13_TDI
//   jtag_slave_TDI -> jtag_master_14_TDI
//   jtag_slave_TDI -> jtag_master_15_TDI
//   (jtag_master_00_TDO,
//    jtag_master_01_TDO,
//    jtag_master_02_TDO,
//    jtag_master_03_TDO,
//    jtag_master_04_TDO,
//    jtag_master_05_TDO,
//    jtag_master_06_TDO,
//    jtag_master_07_TDO,
//    jtag_master_08_TDO,
//    jtag_master_09_TDO,
//    jtag_master_10_TDO,
//    jtag_master_11_TDO,
//    jtag_master_12_TDO,
//    jtag_master_13_TDO,
//    jtag_master_14_TDO,
//    jtag_master_15_TDO) -> jtag_slave_TDO
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkJTAG_switch(ACLK,
		     ARESETN,

		     slave_select,

		     jtag_slave_TCK,

		     jtag_slave_TMS,

		     jtag_slave_TDI,

		     jtag_slave_TDO,

		     jtag_master_00_TCK,

		     jtag_master_00_TMS,

		     jtag_master_00_TDI,

		     jtag_master_00_TDO,

		     jtag_master_01_TCK,

		     jtag_master_01_TMS,

		     jtag_master_01_TDI,

		     jtag_master_01_TDO,

		     jtag_master_02_TCK,

		     jtag_master_02_TMS,

		     jtag_master_02_TDI,

		     jtag_master_02_TDO,

		     jtag_master_03_TCK,

		     jtag_master_03_TMS,

		     jtag_master_03_TDI,

		     jtag_master_03_TDO,

		     jtag_master_04_TCK,

		     jtag_master_04_TMS,

		     jtag_master_04_TDI,

		     jtag_master_04_TDO,

		     jtag_master_05_TCK,

		     jtag_master_05_TMS,

		     jtag_master_05_TDI,

		     jtag_master_05_TDO,

		     jtag_master_06_TCK,

		     jtag_master_06_TMS,

		     jtag_master_06_TDI,

		     jtag_master_06_TDO,

		     jtag_master_07_TCK,

		     jtag_master_07_TMS,

		     jtag_master_07_TDI,

		     jtag_master_07_TDO,

		     jtag_master_08_TCK,

		     jtag_master_08_TMS,

		     jtag_master_08_TDI,

		     jtag_master_08_TDO,

		     jtag_master_09_TCK,

		     jtag_master_09_TMS,

		     jtag_master_09_TDI,

		     jtag_master_09_TDO,

		     jtag_master_10_TCK,

		     jtag_master_10_TMS,

		     jtag_master_10_TDI,

		     jtag_master_10_TDO,

		     jtag_master_11_TCK,

		     jtag_master_11_TMS,

		     jtag_master_11_TDI,

		     jtag_master_11_TDO,

		     jtag_master_12_TCK,

		     jtag_master_12_TMS,

		     jtag_master_12_TDI,

		     jtag_master_12_TDO,

		     jtag_master_13_TCK,

		     jtag_master_13_TMS,

		     jtag_master_13_TDI,

		     jtag_master_13_TDO,

		     jtag_master_14_TCK,

		     jtag_master_14_TMS,

		     jtag_master_14_TDI,

		     jtag_master_14_TDO,

		     jtag_master_15_TCK,

		     jtag_master_15_TMS,

		     jtag_master_15_TDI,

		     jtag_master_15_TDO);
  parameter [4 : 0] jtag_master = 5'b0;
  input  ACLK;
  input  ARESETN;

  // action method slave_select_action
  input  [4 : 0] slave_select;

  // action method jtag_slave_tck_action
  input  jtag_slave_TCK;

  // action method jtag_slave_tms_action
  input  jtag_slave_TMS;

  // action method jtag_slave_tdi_action
  input  jtag_slave_TDI;

  // value method jtag_slave_tdo
  output jtag_slave_TDO;

  // value method jtag_master_00_tck
  output jtag_master_00_TCK;

  // value method jtag_master_00_tms
  output jtag_master_00_TMS;

  // value method jtag_master_00_tdi
  output jtag_master_00_TDI;

  // action method jtag_master_00_tdo_action
  input  jtag_master_00_TDO;

  // value method jtag_master_01_tck
  output jtag_master_01_TCK;

  // value method jtag_master_01_tms
  output jtag_master_01_TMS;

  // value method jtag_master_01_tdi
  output jtag_master_01_TDI;

  // action method jtag_master_01_tdo_action
  input  jtag_master_01_TDO;

  // value method jtag_master_02_tck
  output jtag_master_02_TCK;

  // value method jtag_master_02_tms
  output jtag_master_02_TMS;

  // value method jtag_master_02_tdi
  output jtag_master_02_TDI;

  // action method jtag_master_02_tdo_action
  input  jtag_master_02_TDO;

  // value method jtag_master_03_tck
  output jtag_master_03_TCK;

  // value method jtag_master_03_tms
  output jtag_master_03_TMS;

  // value method jtag_master_03_tdi
  output jtag_master_03_TDI;

  // action method jtag_master_03_tdo_action
  input  jtag_master_03_TDO;

  // value method jtag_master_04_tck
  output jtag_master_04_TCK;

  // value method jtag_master_04_tms
  output jtag_master_04_TMS;

  // value method jtag_master_04_tdi
  output jtag_master_04_TDI;

  // action method jtag_master_04_tdo_action
  input  jtag_master_04_TDO;

  // value method jtag_master_05_tck
  output jtag_master_05_TCK;

  // value method jtag_master_05_tms
  output jtag_master_05_TMS;

  // value method jtag_master_05_tdi
  output jtag_master_05_TDI;

  // action method jtag_master_05_tdo_action
  input  jtag_master_05_TDO;

  // value method jtag_master_06_tck
  output jtag_master_06_TCK;

  // value method jtag_master_06_tms
  output jtag_master_06_TMS;

  // value method jtag_master_06_tdi
  output jtag_master_06_TDI;

  // action method jtag_master_06_tdo_action
  input  jtag_master_06_TDO;

  // value method jtag_master_07_tck
  output jtag_master_07_TCK;

  // value method jtag_master_07_tms
  output jtag_master_07_TMS;

  // value method jtag_master_07_tdi
  output jtag_master_07_TDI;

  // action method jtag_master_07_tdo_action
  input  jtag_master_07_TDO;

  // value method jtag_master_08_tck
  output jtag_master_08_TCK;

  // value method jtag_master_08_tms
  output jtag_master_08_TMS;

  // value method jtag_master_08_tdi
  output jtag_master_08_TDI;

  // action method jtag_master_08_tdo_action
  input  jtag_master_08_TDO;

  // value method jtag_master_09_tck
  output jtag_master_09_TCK;

  // value method jtag_master_09_tms
  output jtag_master_09_TMS;

  // value method jtag_master_09_tdi
  output jtag_master_09_TDI;

  // action method jtag_master_09_tdo_action
  input  jtag_master_09_TDO;

  // value method jtag_master_10_tck
  output jtag_master_10_TCK;

  // value method jtag_master_10_tms
  output jtag_master_10_TMS;

  // value method jtag_master_10_tdi
  output jtag_master_10_TDI;

  // action method jtag_master_10_tdo_action
  input  jtag_master_10_TDO;

  // value method jtag_master_11_tck
  output jtag_master_11_TCK;

  // value method jtag_master_11_tms
  output jtag_master_11_TMS;

  // value method jtag_master_11_tdi
  output jtag_master_11_TDI;

  // action method jtag_master_11_tdo_action
  input  jtag_master_11_TDO;

  // value method jtag_master_12_tck
  output jtag_master_12_TCK;

  // value method jtag_master_12_tms
  output jtag_master_12_TMS;

  // value method jtag_master_12_tdi
  output jtag_master_12_TDI;

  // action method jtag_master_12_tdo_action
  input  jtag_master_12_TDO;

  // value method jtag_master_13_tck
  output jtag_master_13_TCK;

  // value method jtag_master_13_tms
  output jtag_master_13_TMS;

  // value method jtag_master_13_tdi
  output jtag_master_13_TDI;

  // action method jtag_master_13_tdo_action
  input  jtag_master_13_TDO;

  // value method jtag_master_14_tck
  output jtag_master_14_TCK;

  // value method jtag_master_14_tms
  output jtag_master_14_TMS;

  // value method jtag_master_14_tdi
  output jtag_master_14_TDI;

  // action method jtag_master_14_tdo_action
  input  jtag_master_14_TDO;

  // value method jtag_master_15_tck
  output jtag_master_15_TCK;

  // value method jtag_master_15_tms
  output jtag_master_15_TMS;

  // value method jtag_master_15_tdi
  output jtag_master_15_TDI;

  // action method jtag_master_15_tdo_action
  input  jtag_master_15_TDO;

  // signals for module outputs
  reg jtag_slave_TDO;
  wire jtag_master_00_TCK,
       jtag_master_00_TDI,
       jtag_master_00_TMS,
       jtag_master_01_TCK,
       jtag_master_01_TDI,
       jtag_master_01_TMS,
       jtag_master_02_TCK,
       jtag_master_02_TDI,
       jtag_master_02_TMS,
       jtag_master_03_TCK,
       jtag_master_03_TDI,
       jtag_master_03_TMS,
       jtag_master_04_TCK,
       jtag_master_04_TDI,
       jtag_master_04_TMS,
       jtag_master_05_TCK,
       jtag_master_05_TDI,
       jtag_master_05_TMS,
       jtag_master_06_TCK,
       jtag_master_06_TDI,
       jtag_master_06_TMS,
       jtag_master_07_TCK,
       jtag_master_07_TDI,
       jtag_master_07_TMS,
       jtag_master_08_TCK,
       jtag_master_08_TDI,
       jtag_master_08_TMS,
       jtag_master_09_TCK,
       jtag_master_09_TDI,
       jtag_master_09_TMS,
       jtag_master_10_TCK,
       jtag_master_10_TDI,
       jtag_master_10_TMS,
       jtag_master_11_TCK,
       jtag_master_11_TDI,
       jtag_master_11_TMS,
       jtag_master_12_TCK,
       jtag_master_12_TDI,
       jtag_master_12_TMS,
       jtag_master_13_TCK,
       jtag_master_13_TDI,
       jtag_master_13_TMS,
       jtag_master_14_TCK,
       jtag_master_14_TDI,
       jtag_master_14_TMS,
       jtag_master_15_TCK,
       jtag_master_15_TDI,
       jtag_master_15_TMS;

  // register internal_slave_select
  reg [4 : 0] internal_slave_select;
  wire [4 : 0] internal_slave_select$D_IN;
  wire internal_slave_select$EN;

  // remaining internal signals
  wire NOT_jtag_master_ULE_10_3___d54,
       NOT_jtag_master_ULE_11_8___d59,
       NOT_jtag_master_ULE_12_3___d64,
       NOT_jtag_master_ULE_13_8___d69,
       NOT_jtag_master_ULE_14_3___d74,
       NOT_jtag_master_ULE_15_7___d78,
       NOT_jtag_master_ULE_1___d9,
       NOT_jtag_master_ULE_2_3___d14,
       NOT_jtag_master_ULE_3_8___d19,
       NOT_jtag_master_ULE_4_3___d24,
       NOT_jtag_master_ULE_5_8___d29,
       NOT_jtag_master_ULE_6_3___d34,
       NOT_jtag_master_ULE_7_8___d39,
       NOT_jtag_master_ULE_8_3___d44,
       NOT_jtag_master_ULE_9_8___d49;

  // value method jtag_slave_tdo
  always@(internal_slave_select or
	  NOT_jtag_master_ULE_15_7___d78 or
	  jtag_master_15_TDO or
	  jtag_master or
	  jtag_master_00_TDO or
	  NOT_jtag_master_ULE_1___d9 or
	  jtag_master_01_TDO or
	  NOT_jtag_master_ULE_2_3___d14 or
	  jtag_master_02_TDO or
	  NOT_jtag_master_ULE_3_8___d19 or
	  jtag_master_03_TDO or
	  NOT_jtag_master_ULE_4_3___d24 or
	  jtag_master_04_TDO or
	  NOT_jtag_master_ULE_5_8___d29 or
	  jtag_master_05_TDO or
	  NOT_jtag_master_ULE_6_3___d34 or
	  jtag_master_06_TDO or
	  NOT_jtag_master_ULE_7_8___d39 or
	  jtag_master_07_TDO or
	  NOT_jtag_master_ULE_8_3___d44 or
	  jtag_master_08_TDO or
	  NOT_jtag_master_ULE_9_8___d49 or
	  jtag_master_09_TDO or
	  NOT_jtag_master_ULE_10_3___d54 or
	  jtag_master_10_TDO or
	  NOT_jtag_master_ULE_11_8___d59 or
	  jtag_master_11_TDO or
	  NOT_jtag_master_ULE_12_3___d64 or
	  jtag_master_12_TDO or
	  NOT_jtag_master_ULE_13_8___d69 or
	  jtag_master_13_TDO or
	  NOT_jtag_master_ULE_14_3___d74 or jtag_master_14_TDO)
  begin
    case (internal_slave_select)
      5'd0: jtag_slave_TDO = jtag_master != 5'd0 && jtag_master_00_TDO;
      5'd1: jtag_slave_TDO = NOT_jtag_master_ULE_1___d9 && jtag_master_01_TDO;
      5'd2:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_2_3___d14 && jtag_master_02_TDO;
      5'd3:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_3_8___d19 && jtag_master_03_TDO;
      5'd4:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_4_3___d24 && jtag_master_04_TDO;
      5'd5:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_5_8___d29 && jtag_master_05_TDO;
      5'd6:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_6_3___d34 && jtag_master_06_TDO;
      5'd7:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_7_8___d39 && jtag_master_07_TDO;
      5'd8:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_8_3___d44 && jtag_master_08_TDO;
      5'd9:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_9_8___d49 && jtag_master_09_TDO;
      5'd10:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_10_3___d54 && jtag_master_10_TDO;
      5'd11:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_11_8___d59 && jtag_master_11_TDO;
      5'd12:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_12_3___d64 && jtag_master_12_TDO;
      5'd13:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_13_8___d69 && jtag_master_13_TDO;
      5'd14:
	  jtag_slave_TDO =
	      NOT_jtag_master_ULE_14_3___d74 && jtag_master_14_TDO;
      default: jtag_slave_TDO =
		   NOT_jtag_master_ULE_15_7___d78 && jtag_master_15_TDO;
    endcase
  end

  // value method jtag_master_00_tck
  assign jtag_master_00_TCK =
	     jtag_master != 5'd0 &&
	     (internal_slave_select != 5'd0 || jtag_slave_TCK) ;

  // value method jtag_master_00_tms
  assign jtag_master_00_TMS =
	     jtag_master != 5'd0 &&
	     (internal_slave_select != 5'd0 || jtag_slave_TMS) ;

  // value method jtag_master_00_tdi
  assign jtag_master_00_TDI =
	     jtag_master != 5'd0 && internal_slave_select == 5'd0 &&
	     jtag_slave_TDI ;

  // value method jtag_master_01_tck
  assign jtag_master_01_TCK =
	     NOT_jtag_master_ULE_1___d9 &&
	     (internal_slave_select != 5'd1 || jtag_slave_TCK) ;

  // value method jtag_master_01_tms
  assign jtag_master_01_TMS =
	     NOT_jtag_master_ULE_1___d9 &&
	     (internal_slave_select != 5'd1 || jtag_slave_TMS) ;

  // value method jtag_master_01_tdi
  assign jtag_master_01_TDI =
	     NOT_jtag_master_ULE_1___d9 && internal_slave_select == 5'd1 &&
	     jtag_slave_TDI ;

  // value method jtag_master_02_tck
  assign jtag_master_02_TCK =
	     NOT_jtag_master_ULE_2_3___d14 &&
	     (internal_slave_select != 5'd2 || jtag_slave_TCK) ;

  // value method jtag_master_02_tms
  assign jtag_master_02_TMS =
	     NOT_jtag_master_ULE_2_3___d14 &&
	     (internal_slave_select != 5'd2 || jtag_slave_TMS) ;

  // value method jtag_master_02_tdi
  assign jtag_master_02_TDI =
	     NOT_jtag_master_ULE_2_3___d14 && internal_slave_select == 5'd2 &&
	     jtag_slave_TDI ;

  // value method jtag_master_03_tck
  assign jtag_master_03_TCK =
	     NOT_jtag_master_ULE_3_8___d19 &&
	     (internal_slave_select != 5'd3 || jtag_slave_TCK) ;

  // value method jtag_master_03_tms
  assign jtag_master_03_TMS =
	     NOT_jtag_master_ULE_3_8___d19 &&
	     (internal_slave_select != 5'd3 || jtag_slave_TMS) ;

  // value method jtag_master_03_tdi
  assign jtag_master_03_TDI =
	     NOT_jtag_master_ULE_3_8___d19 && internal_slave_select == 5'd3 &&
	     jtag_slave_TDI ;

  // value method jtag_master_04_tck
  assign jtag_master_04_TCK =
	     NOT_jtag_master_ULE_4_3___d24 &&
	     (internal_slave_select != 5'd4 || jtag_slave_TCK) ;

  // value method jtag_master_04_tms
  assign jtag_master_04_TMS =
	     NOT_jtag_master_ULE_4_3___d24 &&
	     (internal_slave_select != 5'd4 || jtag_slave_TMS) ;

  // value method jtag_master_04_tdi
  assign jtag_master_04_TDI =
	     NOT_jtag_master_ULE_4_3___d24 && internal_slave_select == 5'd4 &&
	     jtag_slave_TDI ;

  // value method jtag_master_05_tck
  assign jtag_master_05_TCK =
	     NOT_jtag_master_ULE_5_8___d29 &&
	     (internal_slave_select != 5'd5 || jtag_slave_TCK) ;

  // value method jtag_master_05_tms
  assign jtag_master_05_TMS =
	     NOT_jtag_master_ULE_5_8___d29 &&
	     (internal_slave_select != 5'd5 || jtag_slave_TMS) ;

  // value method jtag_master_05_tdi
  assign jtag_master_05_TDI =
	     NOT_jtag_master_ULE_5_8___d29 && internal_slave_select == 5'd5 &&
	     jtag_slave_TDI ;

  // value method jtag_master_06_tck
  assign jtag_master_06_TCK =
	     NOT_jtag_master_ULE_6_3___d34 &&
	     (internal_slave_select != 5'd6 || jtag_slave_TCK) ;

  // value method jtag_master_06_tms
  assign jtag_master_06_TMS =
	     NOT_jtag_master_ULE_6_3___d34 &&
	     (internal_slave_select != 5'd6 || jtag_slave_TMS) ;

  // value method jtag_master_06_tdi
  assign jtag_master_06_TDI =
	     NOT_jtag_master_ULE_6_3___d34 && internal_slave_select == 5'd6 &&
	     jtag_slave_TDI ;

  // value method jtag_master_07_tck
  assign jtag_master_07_TCK =
	     NOT_jtag_master_ULE_7_8___d39 &&
	     (internal_slave_select != 5'd7 || jtag_slave_TCK) ;

  // value method jtag_master_07_tms
  assign jtag_master_07_TMS =
	     NOT_jtag_master_ULE_7_8___d39 &&
	     (internal_slave_select != 5'd7 || jtag_slave_TMS) ;

  // value method jtag_master_07_tdi
  assign jtag_master_07_TDI =
	     NOT_jtag_master_ULE_7_8___d39 && internal_slave_select == 5'd7 &&
	     jtag_slave_TDI ;

  // value method jtag_master_08_tck
  assign jtag_master_08_TCK =
	     NOT_jtag_master_ULE_8_3___d44 &&
	     (internal_slave_select != 5'd8 || jtag_slave_TCK) ;

  // value method jtag_master_08_tms
  assign jtag_master_08_TMS =
	     NOT_jtag_master_ULE_8_3___d44 &&
	     (internal_slave_select != 5'd8 || jtag_slave_TMS) ;

  // value method jtag_master_08_tdi
  assign jtag_master_08_TDI =
	     NOT_jtag_master_ULE_8_3___d44 && internal_slave_select == 5'd8 &&
	     jtag_slave_TDI ;

  // value method jtag_master_09_tck
  assign jtag_master_09_TCK =
	     NOT_jtag_master_ULE_9_8___d49 &&
	     (internal_slave_select != 5'd9 || jtag_slave_TCK) ;

  // value method jtag_master_09_tms
  assign jtag_master_09_TMS =
	     NOT_jtag_master_ULE_9_8___d49 &&
	     (internal_slave_select != 5'd9 || jtag_slave_TMS) ;

  // value method jtag_master_09_tdi
  assign jtag_master_09_TDI =
	     NOT_jtag_master_ULE_9_8___d49 && internal_slave_select == 5'd9 &&
	     jtag_slave_TDI ;

  // value method jtag_master_10_tck
  assign jtag_master_10_TCK =
	     NOT_jtag_master_ULE_10_3___d54 &&
	     (internal_slave_select != 5'd10 || jtag_slave_TCK) ;

  // value method jtag_master_10_tms
  assign jtag_master_10_TMS =
	     NOT_jtag_master_ULE_10_3___d54 &&
	     (internal_slave_select != 5'd10 || jtag_slave_TMS) ;

  // value method jtag_master_10_tdi
  assign jtag_master_10_TDI =
	     NOT_jtag_master_ULE_10_3___d54 &&
	     internal_slave_select == 5'd10 &&
	     jtag_slave_TDI ;

  // value method jtag_master_11_tck
  assign jtag_master_11_TCK =
	     NOT_jtag_master_ULE_11_8___d59 &&
	     (internal_slave_select != 5'd11 || jtag_slave_TCK) ;

  // value method jtag_master_11_tms
  assign jtag_master_11_TMS =
	     NOT_jtag_master_ULE_11_8___d59 &&
	     (internal_slave_select != 5'd11 || jtag_slave_TMS) ;

  // value method jtag_master_11_tdi
  assign jtag_master_11_TDI =
	     NOT_jtag_master_ULE_11_8___d59 &&
	     internal_slave_select == 5'd11 &&
	     jtag_slave_TDI ;

  // value method jtag_master_12_tck
  assign jtag_master_12_TCK =
	     NOT_jtag_master_ULE_12_3___d64 &&
	     (internal_slave_select != 5'd12 || jtag_slave_TCK) ;

  // value method jtag_master_12_tms
  assign jtag_master_12_TMS =
	     NOT_jtag_master_ULE_12_3___d64 &&
	     (internal_slave_select != 5'd12 || jtag_slave_TMS) ;

  // value method jtag_master_12_tdi
  assign jtag_master_12_TDI =
	     NOT_jtag_master_ULE_12_3___d64 &&
	     internal_slave_select == 5'd12 &&
	     jtag_slave_TDI ;

  // value method jtag_master_13_tck
  assign jtag_master_13_TCK =
	     NOT_jtag_master_ULE_13_8___d69 &&
	     (internal_slave_select != 5'd13 || jtag_slave_TCK) ;

  // value method jtag_master_13_tms
  assign jtag_master_13_TMS =
	     NOT_jtag_master_ULE_13_8___d69 &&
	     (internal_slave_select != 5'd13 || jtag_slave_TMS) ;

  // value method jtag_master_13_tdi
  assign jtag_master_13_TDI =
	     NOT_jtag_master_ULE_13_8___d69 &&
	     internal_slave_select == 5'd13 &&
	     jtag_slave_TDI ;

  // value method jtag_master_14_tck
  assign jtag_master_14_TCK =
	     NOT_jtag_master_ULE_14_3___d74 &&
	     (internal_slave_select != 5'd14 || jtag_slave_TCK) ;

  // value method jtag_master_14_tms
  assign jtag_master_14_TMS =
	     NOT_jtag_master_ULE_14_3___d74 &&
	     (internal_slave_select != 5'd14 || jtag_slave_TMS) ;

  // value method jtag_master_14_tdi
  assign jtag_master_14_TDI =
	     NOT_jtag_master_ULE_14_3___d74 &&
	     internal_slave_select == 5'd14 &&
	     jtag_slave_TDI ;

  // value method jtag_master_15_tck
  assign jtag_master_15_TCK =
	     NOT_jtag_master_ULE_15_7___d78 &&
	     (internal_slave_select != 5'd15 || jtag_slave_TCK) ;

  // value method jtag_master_15_tms
  assign jtag_master_15_TMS =
	     NOT_jtag_master_ULE_15_7___d78 &&
	     (internal_slave_select != 5'd15 || jtag_slave_TMS) ;

  // value method jtag_master_15_tdi
  assign jtag_master_15_TDI =
	     NOT_jtag_master_ULE_15_7___d78 &&
	     internal_slave_select == 5'd15 &&
	     jtag_slave_TDI ;

  // register internal_slave_select
  assign internal_slave_select$D_IN = slave_select ;
  assign internal_slave_select$EN = 1'd1 ;

  // remaining internal signals
  assign NOT_jtag_master_ULE_10_3___d54 = jtag_master > 5'd10 ;
  assign NOT_jtag_master_ULE_11_8___d59 = jtag_master > 5'd11 ;
  assign NOT_jtag_master_ULE_12_3___d64 = jtag_master > 5'd12 ;
  assign NOT_jtag_master_ULE_13_8___d69 = jtag_master > 5'd13 ;
  assign NOT_jtag_master_ULE_14_3___d74 = jtag_master > 5'd14 ;
  assign NOT_jtag_master_ULE_15_7___d78 = jtag_master > 5'd15 ;
  assign NOT_jtag_master_ULE_1___d9 = jtag_master > 5'd1 ;
  assign NOT_jtag_master_ULE_2_3___d14 = jtag_master > 5'd2 ;
  assign NOT_jtag_master_ULE_3_8___d19 = jtag_master > 5'd3 ;
  assign NOT_jtag_master_ULE_4_3___d24 = jtag_master > 5'd4 ;
  assign NOT_jtag_master_ULE_5_8___d29 = jtag_master > 5'd5 ;
  assign NOT_jtag_master_ULE_6_3___d34 = jtag_master > 5'd6 ;
  assign NOT_jtag_master_ULE_7_8___d39 = jtag_master > 5'd7 ;
  assign NOT_jtag_master_ULE_8_3___d44 = jtag_master > 5'd8 ;
  assign NOT_jtag_master_ULE_9_8___d49 = jtag_master > 5'd9 ;

  // handling of inlined registers

  always@(posedge ACLK)
  begin
    if (ARESETN == `BSV_RESET_VALUE)
      begin
        internal_slave_select <= `BSV_ASSIGNMENT_DELAY 5'd0;
      end
    else
      begin
        if (internal_slave_select$EN)
	  internal_slave_select <= `BSV_ASSIGNMENT_DELAY
	      internal_slave_select$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    internal_slave_select = 5'h0A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkJTAG_switch

